variable env {}
variable vpc {}
variable tags {}
variable "default_vpc_id" {}
variable "rabbitmq" {}
variable "allow_ssh_cidr" {}
variable "default_vpc_rt" {}
variable "zone_id" {}
variable "rds" {}
variable "kms_key_arn" {}
variable "kms_key_id" {}
variable "elasticache" {}
variable "documentdb" {}
variable "alb" {}
